/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * home1.java
 *
 * Created on 25 Jun, 2022, 11:06:34 AM
 */

package employreg;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GANESH
 */
public class home1 extends javax.swing.JFrame {

    /** Creates new form home1 */
    public home1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gdm = new javax.swing.JRadioButton();
        gdf = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddr = new javax.swing.JTextArea();
        clr = new javax.swing.JButton();
        nxt = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtds = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtph = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dtJoin = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtdesig = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TxtUid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 0, 102));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Gender:");

        gdm.setText("MALE");
        gdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdmMouseClicked(evt);
            }
        });
        gdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdmActionPerformed(evt);
            }
        });

        gdf.setText("FEMALE");
        gdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdfMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("Address:");

        txtaddr.setColumns(20);
        txtaddr.setRows(5);
        jScrollPane1.setViewportView(txtaddr);

        clr.setText("CLEAR");
        clr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrMouseClicked(evt);
            }
        });

        nxt.setText("SAVE");
        nxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nxtMouseClicked(evt);
            }
        });

        jLabel13.setText("desination");

        jLabel14.setText("Phone No");

        jLabel15.setText("Mail id");

        jLabel16.setText("Date of Join");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(926, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(918, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(clr))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(nxt))
                            .addComponent(dtJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(664, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(gdm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gdf))
                                    .addComponent(txtnme, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(252, 252, 252))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                        .addGap(433, 433, 433))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gdf)
                    .addComponent(gdm))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clr)
                    .addComponent(nxt))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REGISTRATION", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("SEARCH EMPLOYEE ID");

        txtdesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesigActionPerformed(evt);
            }
        });
        txtdesig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdesigKeyReleased(evt);
            }
        });

        tblTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SlNo", "Employee ID", "Name", "Date of Joining", "Phone No"
            }
        ));
        jScrollPane2.setViewportView(tblTab);

        jButton1.setText("Delete");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtdesig, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1)))
                .addContainerGap(563, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(222, 222, 222))
        );

        jTabbedPane1.addTab("VIEW", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));

        jLabel7.setText("EMployee ID");

        TxtUid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtUidKeyReleased(evt);
            }
        });

        jLabel3.setText("Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Gender");

        jRadioButton1.setText("MALE");

        jRadioButton2.setText("FEMALE");

        jLabel9.setText("Address");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel11.setText("Designation");

        jLabel12.setText("Phone No");

        jLabel17.setText("Mail ID");

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton2))
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtUid, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addGap(976, 976, 976))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(1142, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(1156, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton2)
                .addContainerGap(972, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(TxtUid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("UPDATE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(204, 153, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("EMPLOYEE MANAGEMENT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gdmActionPerformed

    private void txtdesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesigActionPerformed

    private void gdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdfMouseClicked
        // TODO add your handling code here:
         gdm.setSelected(false);
        gdf.setSelected(true);
    }//GEN-LAST:event_gdfMouseClicked

    private void gdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdmMouseClicked
        // TODO add your handling code here:
         gdf.setSelected(false);
        gdm.setSelected(true);
    }//GEN-LAST:event_gdmMouseClicked

    private void nxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxtMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        DateFormat dateFormat=new SimpleDateFormat("yyyy/MM/dd");
        String dte=dateFormat.format(dtJoin.getDate()).toString();
         if(txtnme.getText().equals("")||txtaddr.getText().equals("")||txtds.getText().equals("")||txtph.getText().equals("")||txtmail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "enter all feilds");
        }
       else
        {
            String gen;
            if(gdm.isSelected())
            {
                gen="MALE";
            }
            else
            {
                gen="FEMALE";
            }

            DBConnection objdb=new DBConnection();
            String qry="INSERT INTO empreg (EmpName,EmpGen,EmpAdr,doj,designation,phoneNo,mail) VALUES "+
                    "('"+txtnme.getText()+"','"+gen+"','"+txtaddr.getText()+"','"+dte+"','"+txtds.getText()+"',"+txtph.getText()+",'"+txtmail.getText()+"')";
            objdb.insertMethod(qry);

            JOptionPane.showMessageDialog(rootPane, "Inserted successfully.");
            txtnme.setText("");
            txtaddr.setText("");
            txtds.setText("");
         txtph.setText("");
         txtmail.setText("");
        }
    }//GEN-LAST:event_nxtMouseClicked

    private void clrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrMouseClicked
        // TODO add your handling code here:
         txtnme.setText("");
         txtaddr.setText("");
         txtds.setText("");
         txtph.setText("");
         txtmail.setText("");
         
    }//GEN-LAST:event_clrMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
       
        for(int j=tblTab.getRowCount()-1;j>=0;j--)
           {
               ((DefaultTableModel)tblTab.getModel()).removeRow(j);
           }

        DBConnection objdb=new DBConnection();
        String qry="SELECT *FROM empreg";
        ResultSet rs=objdb.selectMethod(qry);
        int i=0;
        try {
            while (rs.next()) {
                Vector rawData = new Vector();
                rawData.add(i + 1);
                rawData.add(rs.getString("empid"));
                rawData.add(rs.getString("EmpName"));
                rawData.add(rs.getString("doj"));
                rawData.add(rs.getString("phoneNo"));
                ((DefaultTableModel) tblTab.getModel()).insertRow(i, rawData);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(home1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void txtdesigKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdesigKeyReleased
        // TODO add your handling code here:
        if(txtdesig.getText().equals(""))
        {
        for(int j=tblTab.getRowCount()-1;j>=0;j--)
           {
               ((DefaultTableModel)tblTab.getModel()).removeRow(j);
           }
        DBConnection objdb=new DBConnection();
        String qry="SELECT *FROM empreg";
        ResultSet rs=objdb.selectMethod(qry);
        int i=0;
        try {
            while (rs.next()) {
                Vector rawData = new Vector();
                rawData.add(i + 1);
                rawData.add(rs.getString("empid"));
                rawData.add(rs.getString("EmpName"));
                rawData.add(rs.getString("doj"));
                rawData.add(rs.getString("phoneNo"));
                ((DefaultTableModel) tblTab.getModel()).insertRow(i, rawData);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(home1.class.getName()).log(Level.SEVERE, null, ex);
        }}

 else{
            for(int j=tblTab.getRowCount()-1;j>=0;j--)
           {
               ((DefaultTableModel)tblTab.getModel()).removeRow(j);
           }

        DBConnection objdb=new DBConnection();
        String qry1="SELECT *FROM empreg where empid = '"+txtdesig.getText()+"'";
        ResultSet rs=objdb.selectMethod(qry1);
        int i=0;
        try {
            while (rs.next()) {
                Vector rawData = new Vector();
                rawData.add(i + 1);
                rawData.add(rs.getString("empid"));
                rawData.add(rs.getString("EmpName"));
                rawData.add(rs.getString("doj"));
                rawData.add(rs.getString("phoneNo"));
                ((DefaultTableModel) tblTab.getModel()).insertRow(i, rawData);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(home1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_txtdesigKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        if(tblTab.getSelectedRowCount()>0)
       {
        int rw=tblTab.getSelectedRow();

       int val=Integer.parseInt(tblTab.getValueAt(rw, 1).toString())  ;
       DBConnection objdb=new DBConnection();
        String qry1="DELETE FROM empreg where empid = "+val+"";
        objdb.delMethod(qry1);
          for(int j=tblTab.getRowCount()-1;j>=0;j--)
           {
               ((DefaultTableModel)tblTab.getModel()).removeRow(j);
           }

        
        String qry2="SELECT *FROM empreg"; 
        ResultSet rs=objdb.selectMethod(qry2);
        int i=0;
        try {
            while (rs.next()) {
                Vector rawData = new Vector();
                rawData.add(i + 1);
                rawData.add(rs.getString("empid"));
                rawData.add(rs.getString("EmpName"));
                rawData.add(rs.getString("doj"));
                rawData.add(rs.getString("phoneNo"));
                ((DefaultTableModel) tblTab.getModel()).insertRow(i, rawData);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(home1.class.getName()).log(Level.SEVERE, null, ex);
        }




        //JOptionPane.showMessageDialog(rootPane, ""+val);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void TxtUidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUidKeyReleased
        // TODO add your handling code here:
        //int cnt=0;
        // String  qry= "SELECT Count(empid) as cnt"
                           // + " FROM  empreg WHERE empid="+TxtUid.getText();
       // ResultSet rs=objdb.selectMethod(qry);
        // try{
        // while (rs.next()) {
                     // cnt=rs.getInt("cnt");
                //  }
        // }
         //catch(Exception e)
        // {

        // }

                 // if(cnt>0)

                 // {
        DBConnection objdb=new DBConnection();
       // String qry="SELECT *FROM empreg";
      String qry = "SELECT EmpName,EmpGen,EmpAdr,designation,phoneNo,mail FROM empreg WHERE empid="+TxtUid.getText();
          System.out.print(qry)    ;

      ResultSet rs =objdb.selectMethod(qry);
      try{
          while (rs.next()) {
               jTextField2.setText(rs.getString("EmpName"));
               if (rs.getString("EmpGen").equals("MALE")) {
                jRadioButton1.setSelected(true);
                jRadioButton2.setSelected(false);
            } else {
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(true);
            }
               jTextArea1.setText(rs.getString("EmpAdr"));
               jTextField3.setText(rs.getString("designation"));
               jTextField4.setText(rs.getString("phoneNo"));
               jTextField5.setText(rs.getString("mail"));

          }
      }
      catch(Exception ex)
      {
          
      }




    }//GEN-LAST:event_TxtUidKeyReleased

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        if(TxtUid.getText().equals("")||jTextField2.getText().equals("")||jTextArea1.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
        {
        JOptionPane.showMessageDialog(rootPane, "Please Enter all fields.");
        }
 else
        {
            String gen;
            if(jRadioButton1.isSelected())
            {
                gen="MALE";
            }
            else
            {
                gen="FEMALE";
            }
            DBConnection objdb=new DBConnection();

        String    qry = "UPDATE empreg SET empid="+Integer.parseInt(TxtUid.getText())+ ","+
                    "EmpName='" + jTextField2.getText() + "',EmpGen='"+ gen +"',"+
                    "EmpAdr='" + jTextArea1.getText() + "',designation='" + jTextField3.getText() + "',"+
                    "phoneNo=" + Integer.parseInt(jTextField4.getText())+ " ,mail='"+jTextField5.getText()+"' WHERE empid="+Integer.parseInt(TxtUid.getText());
            objdb.updateMethod(qry);
                System.out.println("\n statement: "+qry);
            JOptionPane.showMessageDialog(rootPane, "Accident Updated Successfully.");
 }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
  //  }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtUid;
    private javax.swing.JButton clr;
    private com.toedter.calendar.JDateChooser dtJoin;
    private javax.swing.JRadioButton gdf;
    private javax.swing.JRadioButton gdm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton nxt;
    private javax.swing.JTable tblTab;
    private javax.swing.JTextArea txtaddr;
    private javax.swing.JTextField txtdesig;
    private javax.swing.JTextField txtds;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnme;
    private javax.swing.JTextField txtph;
    // End of variables declaration//GEN-END:variables

}
